language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install numpy
script:
    - python -m pytest . --cov=.
after_success:
    - coveralls
